apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: customer-profile
  namespace: mae
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=customer-profile"
spec:
  type: service
  lifecycle: experimental
  owner: team-awesome
  system: tanzu-gtt
  providesApis:
    - customer-profile-run
