apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  annotations:
    classclaims.services.apps.tanzu.vmware.com/xrd-name: xpostgresqlinstances.bindable.database.example.org
  finalizers:
  - classclaims.services.apps.tanzu.vmware.com/provision-finalizer
  name: postgres-mae
  namespace: mae
spec:
  classRef:
    name: postgresql-rds
  parameters:
    storageGB: 10